### PR TITLE
Changes for Matlab plugin to compile under macOS.

### PR DESCRIPTION
**Pull request by prennich**
- Modified matlab.cmake
- Replaced FindMatlab.cmake with most recent.
- Added FindPackageHandleStandardArgs.cmake
- Added FindPackageMessage.cmake

### CODE REVIEW

**Comment by abellgithub** [comment]
You don't need to add the "Find..." modules as they should be included with any cmake that meets the PDAL minimum requirements.

**Comment by prennich** [comment]
> You don't need to add the "Find..." modules as they should be included with any cmake that meets the PDAL minimum requirements.

Hmm, I seem to have cmake version 3.29.0, but I needed to have these "Find..." modules here. Not sure what's going on.

**Comment by abellgithub** [comment]
Maybe something is strange with your cmake install and that's the root of the issue?

I have 3.26 and it's in cmake-3.26/Modules/Find...

**Comment by prennich** [comment]
Cmake modules, for me, live here:
/opt/homebrew/Cellar/cmake/3.29.4/share/cmake/Modules/
(I uninstalled and reinstalled which upgraded to 3.29.4)
But, it still seems to need them in the PDAL directory structure in order to configure without errors.

By the way, there's a FindMatlab.cmake module that comes with cmake also. Why does PDAL need that then?

(We're getting a bit out of my league... not sure I'm able to help much more beyond this.)

**Comment by prennich** [comment]
Turns out that if I simply remove the FindMatlab.cmake module all together, then it will configure just fine with the BUILD_PLUGIN_MATLAB set to ON.

Latest commit on this pull-request has FindMatlab.cmake and the FindPackage... modules removed.

But, the ctest tests aren't successful:

1 - pdal_io_matlab_writer_test (Subprocess aborted)
2 - pdal_io_matlab_reader_test (Subprocess aborted)
3 - pdal_filters_matlab_test (Subprocess aborted)

However, the executable still successfully writes a matlab file.

Will now look into why these tests abort...

**Comment by prennich** [comment]
With the verbose flag on for ctest, I get this for the matlab_writer_test:

test 1
        Start   1: pdal_io_matlab_writer_test

1: Test command: /Users/patrick/software/PDAL/build/bin/pdal_io_matlab_writer_test
1: Working Directory: /Users/patrick/software/PDAL/build/bin/..
1: Environment variables: 
1:  PDAL_DRIVER_PATH=/Users/patrick/software/PDAL/build/lib
1: Test timeout computed to be: 10000000
1: dyld[6713]: Library not loaded: @rpath/libpdal_plugin_writer_matlab.17.dylib
1:   Referenced from: <0F42D60B-84E1-3D7B-B33E-19EE4EADD531> /Users/patrick/software/PDAL/build/bin/pdal_io_matlab_writer_test
1:   Reason: tried: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/libpdal_plugin_writer_matlab.17.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/libpdal_plugin_writer_matlab.17.dylib' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/swift:/libpdal_plugin_writer_matlab.17.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/swift:/libpdal_plugin_writer_matlab.17.dylib' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/libpdal_plugin_writer_matlab.17.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/libpdal_plugin_writer_matlab.17.dylib' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/swift:/libpdal_plugin_writer_matlab.17.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/swift:/libpdal_plugin_writer_matlab.17.dylib' (no such file)
  1/134 Test   #1: pdal_io_matlab_writer_test ...................Subprocess aborted***Exception:   0.00 sec


The `PDAL_DRIVER_PATH` seems to be appropriately set, but when it's looking for the .dylib file it's only looking in Xcode.app directories. After building PDAL, the appropriate .dylib file exists in the /Users/patrick/software/PDAL/build/lib folder as indicated by the `PDAL_DRIVER_PATH`.

Any suggestions?

**Comment by prennich** [comment]
In the CMakeLists.txt for the Matlab Plugin I commented out the blocks that looked like this:

    set_target_properties(pdal_io_matlab_writer_test
        PROPERTIES
        INSTALL_RPATH "${CMAKE_CXX_IMPLICIT_LINK_DIRECTORIES}:${MATLAB_LIB_DIR}"
        BUILD_WITH_INSTALL_RPATH true
    )

Now all the Matlab Plugin ctests pass!

The only ctest that doesn't pass is the org_writer_test:

99% tests passed, 1 tests failed out of 136
Total Test time (real) = 167.82 sec
The following tests FAILED:
	 48 - pdal_io_ogr_writer_test (Failed)

But, this seems completely independent of the Matlab Plugin.

I've now commited the changes to the Matlab Plugin CMakeLists.txt file to the branch for this pull-request.

**Comment by hobu** [comment]
> The only ctest that doesn't pass is the org_writer_test:

You can ignore that one.

**Comment by hobu** [comment]
picked back to `2.7-maintenance` at 38cbb3a37dfbc147a4cac46adeb2a0707157a344

**Comment by hobu** [comment]
> Now all the Matlab Plugin ctests pass!

Glad you're going! Thanks for the contribution. It will make it into 2.7.2 and 2.8.0 when they are released.

**Pull request merged**
