### PR TITLE
Add warnings/errors for bad return information in PMF and SMRF

### PR DESCRIPTION
**Pull request by chambbj**
There is a much more efficient, or at least prettier way to do this I'm sure, but I think it gets at the problem we discussed. Partially addresses #2416.

### CODE REVIEW

**Comment by abellgithub** [comment]
I'd rather not backport this to 1.8.  1.8 is done, and this isn't, technically, a bug.

I'm not sure about 1.9 because this changes behaivor -- it's not JUST a warning.

**Comment by hobu** [comment]
Did this make it to 1.9-maintenance?

**Comment by abellgithub** [comment]
No. My concern was that it changed behavior at the last minute and I didn't think it was that important. If you have strong feelings about it, we should talk on Thursday.

**Comment by hobu** [comment]
No reason to not merge this into 2.0 now, correct @abellgithub ?

**Comment by abellgithub** [comment]
Let me look.

**Comment by abellgithub** [comment]
The only way that I see that m_args->returns can be empty is if we're missing the ReturnNumber of NumberOfReturns dimensions.  But we're still looping all the points to check the state of zero's, when we already know.  This seems a waste.  In general, Segmentation::segmentReturns is already looping the points and checking nr/rn, so moving this validation there seems like it would make sense.

The loops that append points are duplicated and could be replaced with `firstView->append(*keptView)`, I think.

**Comment by chambbj** [comment]
@abellgithub switching from `appendPoint` to `append` is easy enough. I'd forgotten this was possible.

I'll look into whether or not it makes sense to move the validation to segmentReturns. IIRC, the need to check the actual values wasn't so much to see if they were all zero, but rather to check if any were zero. I'll look again though.

**Comment by chambbj** [comment]
@abellgithub I think this addresses most of what you pointed out. The only thing I'm left wondering at this point is that this PR currently causes the PMF and SMRF filters to throw an error if we come across zeros in the returns, whereas the segmentReturns function would quietly just add them to the "second" PointView (i.e., the one that is ignored for the purposes of the ground segmentation). I think I just need to decide which is the preferable behavior. Even if we allow them to simply be ignored, warning may still be informative as it could be suspicious for these to exist in the first place. Welcome to suggestions here.

**Pull request merged**
