### PR TITLE
Add the minimal option as documented.

### LINKED ISSUE #2225: readers.rxp: Unexpected argument: "minimal"
Hi and thanks for PDAL. I want to use it to handle .rxp-files. When using the argument `minimal` as [documented](https://pdal.io/stages/readers.rxp.html), I get an error `Unexpected argument: "minimal"`. I'm using the following JSON pipeline from within Python.
```
pipeline_json =
"""{
   "pipeline":[
      {
         "type":"readers.rxp",
         "filename":"180417_090506.rxp",
         "reflectance_as_intensity":true,
         "min_reflectance":20,
         "minimal":true,
         "tag":"icp_reference"
      },
      {
         "type":"readers.rxp",
         "filename":"180417_131456.rxp",
         "reflectance_as_intensity":true,
         "min_reflectance":20,
         "minimal":true,
         "tag":"icp_moving"
      }
   ]
}"""
pipeline = pdal.Pipeline(pipeline_json)
pipeline.validate()
```

### PR DESCRIPTION
**Pull request by abellgithub**
Close #2225

### CODE REVIEW

**Comment by gadomski** [comment]
Is there a filter that can remove dimensions, i.e. the opposite of `filters.ferry`? If so, we should remove the `minimal` option and instead recommend using that filter.

**Comment by gadomski** [comment]
Dumb question: is streaming "enabled by default" i.e. does `readers.rxp` get streaming powers just by existing?

**Comment by abellgithub** [comment]
Not a dumb question.

In order to stream, the class must inherit from Streamable and is then required to implement processOne().

**Comment by abellgithub** [comment]
It would be good to be streamable, but I'd like to commit this for the 1.8 release if it works for you in order to make things consistent.  Making `readers.rxp` streamable can be another ticket.

**Pull request merged**
