### PR TITLE
Clean up CMake configuration

### PR DESCRIPTION
**Pull request by chambbj**
(was #1924)

* Remove unused CMake macros

* Convert one off macros to CMake include files

* Specify C++11 for all targets, disabling extensions

* Modern CMake will now parse version numbers automatically

* osinfo.cmake no longer needed, set C++11 per target instead of globally

* Avoid setting any CXX properties globally

### CODE REVIEW

**Comment by abellgithub** [comment]
What prompts this?

**Comment by chambbj** [comment]
Cleaning up old branches/unresolved PRs. Clearly not urgent - just simplifies our CMake a bit by using built-in stuff in CMake 3.

**Comment by abellgithub** [comment]
I like this.  I was going to do some of it, but wanted to get release out first.  Yours is better.

Is there a ticket to go along with the PR?

**Comment by chambbj** [comment]
No ticket.

**Comment by abellgithub** [comment]
For my own benefit...

Close #2694

**Pull request merged**
