### PR TITLE
Properly quote PG identifiers

### PR DESCRIPTION
**Pull request by strk**
Includes test.
Allows naming tables after filenames with no "pre-washing".

### CODE REVIEW

**Comment by abellgithub** [comment]
There is already Utils::replaceAll().  Also, should probably just run stuff once and use that, rather than embed the function call in every usage.

**Comment by strk** [comment]
I just tried re-implementing the quoters with replaceAll but it enters
an infinite loop.

```
inline std::string pg_quote_identifier(std::string const& name) {               
  //return pg_quote(name, '"');                                                 
  return Utils::replaceAll(name, "\"", "\"\"");                                 
}    
```

Running the quoting once, upfront, would require storing 2 different
versions of each identifier (schema, table, column) as they are both
used as literals (for pointcloud_columns query) and identifiers.

**Comment by strk** [comment]
does travis not build or test pgpointcloud ?

**Comment by strk** [comment]
I've a fix for Utils::replaceAll, whcih should also make it generally faster. Will commit shortly.

**Comment by strk** [comment]
There, now replaceAll is used (once fixed). I hadn't found an existing test for replaceAll and didn't add one.

**Comment by abellgithub** [comment]
Sorry, I already committed something with regard to replaceAll.  Can you explain why you'd get quotes in the filenames?  Seems an odd case.

**Comment by strk** [comment]
Quotes in the table name were put intentionally, to test the SQL quoting.
Once we quote, it's good to do it correctly.

The issue with replaceAll was that it did enter an infinite loop when
the string to be replaced is a substring of the replacement one.
Was that case fixed by your change ?

--strk;

**Comment by strk** [comment]
I've seen your change. It does fix the loop (and shows mine was bogus). Thanks!
I'll rebase this PR against master and force-push.

**Comment by strk** [comment]
Rebased. It's 3 commits. First one adds the quoting methods and makes use of it.
Second and third ensure all configuration options are always used (not directly related to quoting but new code does proper quoting so needs the quoting methods)

**Comment by abellgithub** [comment]
I still don't understand what we're doing.  I get that if you have an embedded single-quote in SQL, it needs to be escaped by using two single-quotes.  But I don't understand why we'd need to escape the double quotes in the context in which we're using them.  They're embedded in the final string that gets passed to the postgres function, right?  These aren't literals that we're embedding.

We need a good test case that shows failure, so that we can make sure that any change we're making actually fixes the problem in question.

**Comment by strk** [comment]
My filename is:

 ``20h64_1x1_raw_004_2010_3003-tcxyzissssa``

Unquoted identifiers cannot contain dashes.

``
strk=# create table a-b (a int);
ERROR:  syntax error at or near "-"
LINE 1: create table a-b (a int);
                      ^
``

There are other characters that you cannot put in unquoted identifiers.
Quoting identifiers allows you to use any character.

``
strk=# create table "a-b" (a int);
CREATE TABLE
``

Double-quotes inside quoted identifiers need be escaped by
using two double-quotes.

**Comment by strk** [comment]
BTW, the test is included. Try running the updated test (pgpointcloudtest.cpp)
against master and you'll get the failure.

Beware of #840, which may actually make testing easier ...

**Pull request merged**
