### PR TITLE
Execute info command as streamable

### PR DESCRIPTION
**Pull request by ahuarte47**
This change allows to execute info command as a streamable stage

### CODE REVIEW

**Comment by abellgithub** [comment]
There are problems with this given the current design of the info kernel. It can cause crashes. Sorry.

I'll open a ticket to do something, but it's more complicated than this.

**Comment by ahuarte47** [comment]
Ok @abellgithub, thanks!

**Comment by abellgithub** [comment]
If you look at the history, you'll see this change was there and then pulled. The issue is that some options assume non-streaming mode (assume a point view exists). The existing code probably needs an overhaul to do this right. If you want to tackle that, let me know, but it's a bit ugly. Thanks for your interest in this!

**Comment by ahuarte47** [comment]
I see it, I am only using "--dimensions" and "--enumerate" options with very large LAS files (~3gb). If you agree and I could detect what options force to "info" to run as standard mode in order to safely set the streamable mode. Of course, if you prefer to do yourself, I do nothing now.

**Pull request closed without merging**
