### PR TITLE
FileUtils: std::codecvt_utf8_utf16 unavailable on mingw

### PR DESCRIPTION
**Pull request by xantares**
fallback to boost::filesystem already needed

ref https://github.com/PDAL/PDAL/issues/3329

### CODE REVIEW

**Review by hobu — CHANGES_REQUESTED** [review]
We have been working over the years to remove the vendored boost implementation and stuff like this makes that harder. Is there no system facility in mingw to do this? I get that it is easy to reach for boost here and be done with it, but we don't want that dependency going forward.

**Comment by xantares** [comment]
turns out if I use char16_t instead of unsigned integer it builds ok

**Comment by abellgithub** [comment]
I don't have any problem with this change, but how does this help MinGW? If `unsigned short` != `uint16_t` I would think there would be some other issues as well.

**Comment by abellgithub** [comment]
Fixed by #3536

**Pull request closed without merging**
