### PR TITLE
[filter.litree]  Try to fix an infinite loop when the seed radius is too little

### PR DESCRIPTION
**Pull request by WhiteSte**
This PR follows from #4318. 

If the seed radius is too little the initial dummy point `n0` is set too near to the tree. The result will be in having |Pi| = 1 and |Ni| = |Ui| . Because of that the algorithm goes into an infinite loop. 

This PR is aimed to solve the above mentioned issue trying to expand automatically the radius whenever this condition occur. For now the radius is increased by 10  `  m_dummyRadius += 10; // decide here how to increase the radius` . It could be possible to change this behaviour scaling it by percentage for example. 

I'm not confident with C/C++, i have no idea on how to test the proposed code, if it could work or not.

### CODE REVIEW

**Comment by chambbj** [comment]
Have you run this on your problem dataset? Did it fix the problem?

The rule for the "dummy radius" is simply that it be "far away" from the initial tree point. Did you try first running with a larger `radius` value (instead of forcing it to grow iteratively as shown here)?

I'm further confused because I thought that you said in #4318 that you solved the problem by actually using a smaller and not larger radius.

I certainly agree that this needs to be handled -- I'm just unsure of the proper solution.

**Comment by WhiteSte** [comment]
> Have you run this on your problem dataset? Did it fix the problem?

I never coded in c/c++, i don't even know how to run it. I just tried a logical workaround. Should i compile myself the entire software in order to test it? 

>The rule for the "dummy radius" is simply that it be "far away" from the initial tree point. Did you try first running with a larger radius value (instead of forcing it to grow iteratively as shown here)?

Yes, running a larger radius solves the problem. The fact is that i saw a lower one gives better results, but at the same time i cannot find a general parameter that fits good for all the datasets are processed. (I'm not running it by hand, i've implemented an automatic solution)

>I'm further confused because I thought that you said in https://github.com/PDAL/PDAL/issues/4318 that you solved the problem by actually using a smaller and not larger radius.

nope in the issues i said the opposite

> I certainly agree that this needs to be handled -- I'm just unsure of the proper solution.

Me aswell :) Do you mean is not the proper solution the fact that the radius automatically grows or how i did it?

**Comment by chambbj** [comment]
> > I'm further confused because I thought that you said in #4318 that you solved the problem by actually using a smaller and not larger radius.
> 
> nope in the issues i said the opposite

I see. I forgot that you had been running with a very small radius initially. Keep in mind that the default is 100 m, not 5 m (first attempt) or 50 m (fix). Interesting that you had better luck with 5 m. Depending on the tree, that seems like it would be quite close to be randomly selecting a point expected to not be part of the current tree segment.

We should keep in mind also that the dummy point isn't guaranteed to be radius distance away in the current implementation. We are simply searching for points within that radius and taking the farthest away. As the points available to the set `U` tend toward zero, this could in fact be much smaller than the requested radius (and subsequently, requesting a larger and larger radius may not actually give you a different answer). I remember thinking it would be nice to simply select the farthest available point at each iteration, but that's quite complex to recompute.

One possibly workaround that I remember considering when the issue was first posted is to skip the point `Pi` that was last attempted and to move on to the next highest available point to see if it had any luck generating a new tree segment. I just never got around to coding that logic.

**Comment by WhiteSte** [comment]
>Interesting that you had better luck with 5 m.

worst luck with 5m. That was the parameter sending the algorithm into the loop.

> I remember thinking it would be nice to simply select the farthest available point at each iteration, but that's quite complex to recompute.

Here i have a dubt about the dummy point: Isn't it setting a constraint in the dataset? (any point farther to it is automatically excluded from being a cluster point). That's why i wanted to reduce the seed radius , in order to speed up the computation,  but maybe my idea is simply wrong?

> move on to the next highest available point 

Also here i'm not really confident with the algorithm, but isn't that creating big bugs? I mean: if you start skipping the highest point, jumping around, it can happen that then all of these points will never be clustered. The descending property seems to me being really important in the concept


> and subsequently, requesting a larger and larger radius may not actually give you a different answer

There could be a check that if the radius exceed the total radius of the dataset everything stops. 

----

Since we are on the topic i'm posting here another "problem". Let me know if it should go inside another issue.
I don't know if this was intentional in the original paper (That i've never read :D) but as a cluster reaches the min amount of points it will be closed and it will start clustering another tree. If you have trees with very different sizes/densities that could lead to the behaviour in the screenshot below . Basically a tree is decomposed in several clusters. 
<details>
  <summary>
    Click to view the screenshot
  </summary>
    Screenshot
</details>

**Comment by chambbj** [comment]
> Isn't it setting a constraint in the dataset? (any point farther to it is automatically excluded from being a cluster point).

Not exactly. There is a separate check for this, which isn't really exposed to users at the moment. Instead, the classification of tree points segments all unclassified points into two sets. The first are those points belonging to the current tree segment, the rest are points that do not belong to the tree. The highest unclassified point is the seed for the tree cluster and the far away dummy point is the seed for the non-tree cluster. Some of the thresholds factor in the distance from the point in question to each of these growing clusters.

> I mean: if you start skipping the highest point, jumping around, it can happen that then all of these points will never be clustered. 

I've not thought through this carefully and certainly haven't testing anything, but my intuition was that if the next highest point (after the failed attempt) was part of the same tree, then the point we just skipped would likely just get grouped with the current attempt. Or maybe that particular point (maybe a tree?) never gets clustered, but at least the others still do. It would be interesting to know which point is actually causing this failure. Might it be that there is high noise in the dataset that is causing problems?

If you want to repost the link to the data, I can take a look. I tried last week and it appeared to be dead.

**Comment by chambbj** [comment]
And for your unrelated issue...

> as a cluster reaches the min amount of points it will be closed and it will start clustering another tree

That isn't how the algorithm works. The minimum number of points doesn't terminate clustering. It ensures that any cluster is _at least_ that many points, but it can certainly continue growing.

You should consider giving the paper a read, although it won't address this particular behavior, which is something we implemented ourselves to ensure that we weren't getting noise clusters output. https://www.maine.gov/geolib/programs/lidar/ForestrySegmenting_Trees.pdf

**Comment by WhiteSte** [comment]
>Might it be that there is high noise in the dataset that is causing problems?
If you want to repost the link to the data, I can take a look. I tried last week and it appeared to be dead.

The dataset is really at high resolution, you can check, I've uploaded it again. There shouldn't be much noise
[las+tif.zip](https://www.swisstransfer.com/d/91e1f9e0-d587-4e59-88ce-bb7bff86387f)

>It ensures that any cluster is at least that many points, but it can certainly continue growing.

Under which circumstances? I will take a deep look to the paper soon

What i'm thinking is that this algorithm works pretty well when you have a lot of trees one near the others, but not when they are isolated . Is that wrong? Because i played a bit with the parameters and i could cluster the tree in the screenshot only increasing the min points required (but of course i miss all the others)

**Comment by hobu** [comment]
#4373 is an attempt to solve the issue.

**Pull request closed without merging**
