### PR TITLE
Adding openssl support in order to activate GCS storage

### PR DESCRIPTION
**Pull request by nicolas-chaulet**
I also updated the Arbiter to the latest bundle. Minor changes.

### CODE REVIEW

**Comment by hobu** [comment]
This needs to be upstreamed into arbiter

**Comment by connormanning** [comment]
It has already - it just hasn't been re-bundled since then.

**Comment by abellgithub** [comment]
IMO this stuff would be much improved if it were done at build level and we could ditch the #ifdef stuff

**Comment by abellgithub** [comment]
This was reverted because it broke builds.  The issue seems to be the find module for SSL, which on some systems finds incompatible SSL libraries incompatible with headers (libraries too old and aren't version checked).  It also broke our windows build for some reason.  No time to investigate that right now.

**Comment by nicolas-chaulet** [comment]
Hi @abellgithub any chance we could add openssl for UNIX only systems? I can submit a new PR with some updates (version 1.1 of openssl and not 1.0 as per this PR)

**Comment by abellgithub** [comment]
I have no issue with it if it works, but if not, I'm not sure that I'm going to have much time to look into it in the short term if not.  Okay?

**Comment by nicolas-chaulet** [comment]
From what I remember the Linux builds were passing, just the Windows one was breaking. Was there something else?

**Comment by abellgithub** [comment]
The cmake find script that I had was having trouble dealing with both openssl 1 and openssl 1.1 (or some such) on the same system, if I recall.  Many systems come with openssl, and requiring the newer version created a conflict that I couldn't resolve in short order.

**Pull request merged**
