### PR TITLE
allow override of inferred drivers in kernels (specify with --driver argument) #1273

### PR DESCRIPTION
**Pull request by hobu**

### CODE REVIEW

**Comment by abellgithub** [comment]
Isn't this kind of a problem if you're dealing with more than one file at a time?  It seems like you need a way to specify a driver for each file.

**Comment by hobu** [comment]
Yes it is still a problem in that scenario, but this puts back functionality that was removed as part of the ProgramArgs refactor.

**Comment by abellgithub** [comment]
Hmmm.  Not sure that was ever there.  I'm pretty sure I didn't remove code like that.  But I have no problem with it.  Could do something positional to make it more robust, I guess.

**Comment by hobu** [comment]
It was this thing in 1.2 
https://github.com/PDAL/PDAL/blob/1.2-maintenance/kernels/info/InfoKernel.cpp#L281

**Comment by abellgithub** [comment]
The change that you made to introduce that was only put on 1.2 maintenance -- never went into master.

**Comment by hobu** [comment]
> The change that you made to introduce that was only put on 1.2 maintenance -- never went into master.

D'oh.

**Pull request merged**
