### PR TITLE
Provide option to apply inverse transformation matrix

### LINKED ISSUE #3126: Inverse of Transformation support in filters.transformation
In certain cases, it would be convenient to apply the inverse of the affine transformation applied using filters.transformation.  We sometimes need to do this when projecting back to the original (raw) data collected in the scanner coordinate system when examining instrument calibration for example.

For forward transformation, 4 by 4 matrix M consists of P a 3 by 3 rotation, and v the 3 by 1 translation:

M = | P    v  |
       |  0   1  |

Inverse is given as:

M^-1 = | P^-1.   (-P^-1)*v |
            |   0                 1     |

### PR DESCRIPTION
**Pull request by chambbj**
Close #3126

### CODE REVIEW

**Comment by hobu** [comment]
Docs need update

**Comment by chambbj** [comment]
> Docs need update

Always forget this...

**Comment by chambbj** [comment]
Done messing with this for now. We can completely replace with Eigen down the line if we deem it necessary.

**Comment by abellgithub** [comment]
If we do more on this, perhaps it makes sense to do quaternions w/translation.

**Comment by chambbj** [comment]
Luckily the Eigen support _should_ make that easier.

**Pull request merged**
