### PR TITLE
Implement SOVERSION naming rules and document behavior 

### PR DESCRIPTION
**Pull request by hobu**
Fixes #3042

### CODE REVIEW

**Comment by hobu** [comment]
This needs to be merged back to `2.1-maintenance` with the SOVERSION properly set to increment what was the last `2.0-maintenance` branch.

**Comment by hobu** [comment]
@sebastic we are planning to release a 2.1.1 maintenance release before the end of June. What would you suggest we do with the SONAME given the broken value that was pushed out for 2.1.0?

**Comment by sebastic** [comment]
The current state of the 2.1-maintenance branch looks fine, it keeps the `SOVERSION` at `10` but also fixes the real file to have the `.10.0.0` suffix instead of `.11`.

If there is an ABI break caused by the changes since 2.1.0 then bump the `SOVERSION` (via `PDAL_SOLIB_MAJOR`) accordingly. Although ABI breakage is not really appropriate for a patch release.

**Comment by hobu** [comment]
> If there is an ABI break caused by the changes since 2.1.0

This is not expected at all.

**Pull request merged**
