### PR TITLE
dont new up our data vector in readers.icebridge, as it was a mismatc…

### PR DESCRIPTION
**Pull request by hobu**
…hed delete[]

### CODE REVIEW

**Comment by hobu** [comment]
picked back to `2.5-maintenance` at d016e9c1b9e1ec1adb51a8fd5750b730d9372105

**Comment by abellgithub** [comment]
I don't know what the problem was here, but I would caution that this seems like it would potentially be a really large stack allocation. On OSX this can be an issue, especially if this happens not to be running in the main thread.

**Comment by hobu** [comment]
```
In file included from /usr/include/c++/13.1.1/memory:78,
                 from /data/vendor/gtest/include/gtest/gtest.h:54,
                 from /data/pdal/pdal_test_main.hpp:36,
                 from /data/test/unit/io/LasReaderTest.cpp:35:
In member function 'void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = char]',
    inlined from 'std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = char; _Dp = std::default_delete<char>]' at /usr/include/c++/13.1.1/bits/unique_ptr.h:404:17,
    inlined from 'virtual void LasReaderTest_lazperf_Test::TestBody()' at /data/test/unit/io/LasReaderTest.cpp:476:51:
/usr/include/c++/13.1.1/bits/unique_ptr.h:99:9: warning: 'void operator delete(void*, std::size_t)' called on pointer returned from a mismatched allocation function [-Wmismatched-new-delete]
   99 |         delete __ptr;
      |         ^~~~~~~~~~~~
/data/test/unit/io/LasReaderTest.cpp: In member function 'virtual void LasReaderTest_lazperf_Test::TestBody()':
/data/test/unit/io/LasReaderTest.cpp:476:50: note: returned from 'void* operator new [](std::size_t)'
  476 |     std::unique_ptr<char> buf2(new char[pointSize]);
      |                                                  ^
In member function 'void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = char]',
    inlined from 'std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = char; _Dp = std::default_delete<char>]' at /usr/include/c++/13.1.1/bits/unique_ptr.h:404:17,
    inlined from 'virtual void LasReaderTest_lazperf_Test::TestBody()' at /data/test/unit/io/LasReaderTest.cpp:475:51:
/usr/include/c++/13.1.1/bits/unique_ptr.h:99:9: warning: 'void operator delete(void*, std::size_t)' called on pointer returned from a mismatched allocation function [-Wmismatched-new-delete]
   99 |         delete __ptr;
      |         ^~~~~~~~~~~~
/data/test/unit/io/LasReaderTest.cpp: In member function 'virtual void LasReaderTest_lazperf_Test::TestBody()':
/data/test/unit/io/LasReaderTest.cpp:475:50: note: returned from 'void* operator new [](std::size_t)'
  475 |     std::unique_ptr<char> buf1(new char[pointSize]);
      |                                                  ^
In member function 'void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = char]',
    inlined from 'std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = char; _Dp = std::default_delete<char>]' at /usr/include/c++/13.1.1/bits/unique_ptr.h:404:17,
    inlined from 'virtual void LasReaderTest_lazperf_Test::TestBody()' at /data/test/unit/io/LasReaderTest.cpp:476:51:
/usr/include/c++/13.1.1/bits/unique_ptr.h:99:9: warning: 'void operator delete(void*, std::size_t)' called on pointer returned from a mismatched allocation function [-Wmismatched-new-delete]
   99 |         delete __ptr;
      |         ^~~~~~~~~~~~
/data/test/unit/io/LasReaderTest.cpp: In member function 'virtual void LasReaderTest_lazperf_Test::TestBody()':
/data/test/unit/io/LasReaderTest.cpp:476:50: note: returned from 'void* operator new [](std::size_t)'
  476 |     std::unique_ptr<char> buf2(new char[pointSize]);
      |                                                  ^
In member function 'void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = char]',
    inlined from 'std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = char; _Dp = std::default_delete<char>]' at /usr/include/c++/13.1.1/bits/unique_ptr.h:404:17,
    inlined from 'virtual void LasReaderTest_lazperf_Test::TestBody()' at /data/test/unit/io/LasReaderTest.cpp:475:51:
/usr/include/c++/13.1.1/bits/unique_ptr.h:99:9: warning: 'void operator delete(void*, std::size_t)' called on pointer returned from a mismatched allocation function [-Wmismatched-new-delete]
   99 |         delete __ptr;
      |         ^~~~~~~~~~~~
/data/test/unit/io/LasReaderTest.cpp: In member function 'virtual void LasReaderTest_lazperf_Test::TestBody()':
/data/test/unit/io/LasReaderTest.cpp:475:50: note: returned from 'void* operator new [](std::size_t)'
  475 |     std::unique_ptr<char> buf1(new char[pointSize]);
```

Alpine was complaining about mismatched deletes.

**Comment by abellgithub** [comment]
Oh, this is my bad. It's a vector instead of an array. It'll go on the heap. The previous stuff can be corrected, but there's no need.

**Pull request merged**
