### PR TITLE
Create Omni kernel

### PR DESCRIPTION
**Pull request by chambbj**
Just specify `--input` and `--output` for the input/output file names, and `--filter` for the filter type you'd like. Substitution can be used to modify filter-specific parameters.

### CODE REVIEW

**Comment by abellgithub** [comment]
Isn't this really the same as the translate kernel without the special options that the translate kernel has?

**Comment by chambbj** [comment]
Similar I guess. Though I don't remember translate being able to
dynamically specify the filter as was suggested in #962.

**Comment by abellgithub** [comment]
On Mon, Aug 17, 2015 at 2:52 PM, chambbj <notifications@github.com> wrote:

> Similar I guess. Though I don't remember translate being able to
> dynamically specify the filter as was suggested in #962.
>

No.  Just wondering if it should.  We could perhaps get rid of the
specialized stuff.

-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by chambbj** [comment]
Closing for now. Expect to reopen in the future.

**Pull request closed without merging**
