### PR TITLE
add 'count' metadata to readers.bpf metadata output

### PR DESCRIPTION
**Pull request by hobu**

### CODE REVIEW

**Comment by abellgithub** [comment]
I don't care, but `pdal info --summary` calls it `num_points`.

**Comment by hobu** [comment]
> I don't care, but pdal info --summary calls it num_points.

`readers.las` adds it as `count`, so I followed suit with that. Also, yes, the count is available as `num_points` via `--summary`, but if you are doing something like `--pipeline-serialization` you might need that count pushed there.

**Comment by abellgithub** [comment]
Aok. Just was letting you know that it was different. You could probably also do something for all readers if you want.

**Comment by hobu** [comment]
> You could probably also do something for all readers if you want.

It would be a good idea to normalize these.

**Comment by hobu** [comment]
Picked back to `2.4-maintenance` with 4604297a94b1e32d66734417556e8bbddfd05ebc

**Pull request merged**
