### PR TITLE
build config for filters.cpd STANDALONE

### PR DESCRIPTION
**Pull request by hobu**

### CODE REVIEW

**Comment by hobu** [comment]
picked back to `2.7-maintenance` at ee58b5754526325fba05e49f68f4abad1742503f

**Comment by PureTryOut** [comment]
Hey @hobu this broke the build on Alpine Linux:

```
ninja: job failed: : && /usr/bin/g++ -Os -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_ENABLE_HARDENED_MODE=1 -fno-plt -O2 -Wl,--as-needed,-O1,--sort-common -Wl,-z,pack-relative-relocs test/unit/CMakeFiles/pdal_test_support.dir/Support.cpp.o plugins/cpd/CMakeFiles/pdal_filters_cpd_test.dir/test/CpdFilterTest.cpp.o -o bin/pdal_filters_cpd_test  -Wl,-rpath,/builds/alpine/aports/community/pdal/src/PDAL-2.7.2-src/build/lib  lib/libpdalcpp.so.17.1.0  lib/libgtest.a  /usr/lib/libcpd.so.0.5.5  /usr/lib/libfgt.so.0.4.11 && :
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: plugins/cpd/CMakeFiles/pdal_filters_cpd_test.dir/test/CpdFilterTest.cpp.o: warning: relocation against `_ZTTN4pdal9CpdFilterE' in read-only section `.text'
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: plugins/cpd/CMakeFiles/pdal_filters_cpd_test.dir/test/CpdFilterTest.cpp.o: in function `pdal::(anonymous namespace)::newFilter()':
CpdFilterTest.cpp:(.text+0x305): undefined reference to `VTT for pdal::CpdFilter'
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: CpdFilterTest.cpp:(.text+0x315): undefined reference to `vtable for pdal::CpdFilter'
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: plugins/cpd/CMakeFiles/pdal_filters_cpd_test.dir/test/CpdFilterTest.cpp.o: in function `pdal::CpdFilterTest_DefaultMethod_Test::TestBody()':
CpdFilterTest.cpp:(.text+0x27ea): undefined reference to `pdal::CpdFilter::defaultMethod[abi:cxx11]()'
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: plugins/cpd/CMakeFiles/pdal_filters_cpd_test.dir/test/CpdFilterTest.cpp.o: in function `pdal::CpdFilterTest_DefaultIdentity_Test::TestBody()':
CpdFilterTest.cpp:(.text+0x2d3c): undefined reference to `pdal::CpdFilter::defaultMethod[abi:cxx11]()'
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
ninja: subcommand failed
```

I've reverted this PR in our package for now to be able to update again. We do not use a standalone build.

**Comment by hobu** [comment]
I hadn't realized anyone was packaging CPD anywhere.

The compile line looks like maybe `-std=c++17` isn't being set. I will try to replicate

**Comment by hobu** [comment]
replicated. Fix upcoming.

**Comment by hobu** [comment]
Fixed in https://github.com/PDAL/PDAL/pull/4439

**Comment by PureTryOut** [comment]
I inherited this package from someone else, I suppose someone has a use-case for it :sweat_smile: 

That does seem to do the job, thanks!

**Pull request merged**
