### PR TITLE
Windows shut the hell up

### PR DESCRIPTION
**Pull request by hobu**
Turn off some annoying windows warnings so we can see things in the output.

### CODE REVIEW

**Comment by abellgithub** [comment]
4251 looks like a non-exported DLL warning.  This is something kind of important.

**Comment by hobu** [comment]
> 4251 looks like a non-exported DLL warning. This is something kind of important.

We emit tons of them and never do anything about them.

**Comment by abellgithub** [comment]
We never had these before. What has changed?

**Comment by hobu** [comment]
> We never had these before. What has changed?

Arbiter emits a bunch of them and and has done so for a very long time. See https://ci.appveyor.com/api/buildjobs/1uf6r43s2julrxu5/log

**Comment by abellgithub** [comment]
Arbiter should be fixed.

**Comment by abellgithub** [comment]
Closing in favor of a mixture of this PR and the previous one that static-cast tons of crap.

**Pull request closed without merging**
