### PR TITLE
Try installing postgresql server headers

### PR DESCRIPTION
**Pull request by strk**
Empirical attempt at having travis test pgpointcloud (#839) -- not yet ready for merge

### CODE REVIEW

**Comment by strk** [comment]
Ready for merge as soon as Travis goes green (should be green already)

**Comment by hobu** [comment]
hmm, it failed. Did it run out of cpu time?

**Comment by gadomski** [comment]
/me restarts the build

We've been over this ground before, but it seems like we're again bumping up against the "how much effort to we go through to CI the plugins?" This patch doesn't seem too bad (just `apt-get`ting the postegres server and installing pgpointcloud from source) but there's a couple of other plugins that might be a similar level of complexity that we *aren't* testing (e.g. sqlite, p2g, hexer...).

I wonder how much pain would we inflict upon ourselves by making a `PDAL/PDAL-plugins` repository, where we could stash all plugins that we *don't* CI (e.g. rivlib, mrsid...). Just musing...the seemingly arbitrary way we test some plugins but not others makes my anal-rentitive side twitch a bit :-P...

**Comment by strk** [comment]
It now passed. Can't tell about a separate repo.

**Comment by chambbj** [comment]
@gadomski This probably deserves it's own issue/thread, but I tend to agree with testing more plugins if we can. I fear that separating them might lead to neglect. I know that some of the closed plugins are already outdated. This probably settles down some after a formal release, and is certainly mitigated if we set up a corresponding CI configuration for the separate plugins repo.

If we keep the plugins in PDAL/PDAL, I think we may be able to save some Travis clock cycles by doing the following:

1) Pretty sure we no longer need to build cmake and ninja from source. I'm pretty sure this explains the delta between gcc and clang build times.
2) Though we lose some granularity, we could combine the optional components ON/OFF tests in the build script for each compiler. This would really just save on machine setup. I'm guessing we could also make sure that if optional components OFF fails, we do not proceed to optional components ON.

Are these steps alone enough for us to turn on more dependencies? Maybe. PCL without a current distribution will probably always time out. Even with binaries, it likely won't be built the way we need it.

**Comment by strk** [comment]
Could it make sense to also build with optimizations turned off ? (-O0)

**Comment by gadomski** [comment]
Moved plugin discussion to #851. This PR could be merged, or could be delayed until we come to some decision on #851. I have no preference either way.

**Comment by chambbj** [comment]
Assuming we changed nothing with the plugin testing strategy for now, it looks like there is very little overhead in turning this one on.

**Pull request merged**
