### PR TITLE
TileDB: Add append option to writer

### PR DESCRIPTION
**Pull request by normanb**
This change adds the option to append to an existing TileDB array. This change is useful when merging datasets.

### CODE REVIEW

**Comment by abellgithub** [comment]
Do you need/want some check to make sure that the existing attributes are the same as the new ones when appending?

**Comment by normanb** [comment]
@abellgithub it is going to throw an exception https://github.com/TileDB-Inc/TileDB/blob/88b047879ab4696ecc84042ea6803d17526fc8be/tiledb/sm/query/writer.cc#L473 in the case the attributes are not matching. Do you want me to add this in the PDAL driver as well?

**Comment by abellgithub** [comment]
No.  If you want, it would be nice to catch TileDB exceptions and rethrow wrapped in a PDAL exception so that the built-in handling we have for those gets to run, but not a big deal.

**Comment by normanb** [comment]
@abellgithub  I will look to catch the error and rethrow as a PDAL exception, I won't get to this until tomorrow.

**Pull request merged**
