### PR TITLE
Sqlite error handling

### LINKED ISSUE #927: Improve SQLiteCommon error handling
The sqlite wrapper class should handle all possible return codes from the underlying sqlite object, and it should handle them in the same way.

There is a missing finalize() call at the end of insert(), which causes random bits of havoc when mixing insert() and query() operations, since m_statement is shared between them. We should explicitly null out m_statement, just to make durned sure it's okay to reuse.

### PR DESCRIPTION
**Pull request by mpgerlek**
fixes #927

- handle error returns consistently
- always call finalize()
- fix test case to flush files

### CODE REVIEW

**Comment by abellgithub** [comment]
A bunch of the error messages don't really say what's wrong, just where the error occurred.  OK for a programmer, but less OK for others.  Perhaps something in English that might make sense along with something to help when creating a ticket?

**Comment by mpgerlek** [comment]
I didn't intend to change any of the error messages -- which ones are you talking about?

**Comment by abellgithub** [comment]
Maybe they got moved and I didn't realize.  I just saw stuff like: "sqlite3_step" and "sqlite3_finalize".  Not sure the best thing to display, though.

**Comment by mpgerlek** [comment]
Okay, yes, I added those to indicate which functions were causing the problem - admittedly a programmer-biased view, but more than we had before.

If you can point me to an example of the preferred style for error messages, I'd be happy to upgrade these ones.

**Comment by abellgithub** [comment]
Well, you'd probably know better.  Maybe something like "Error inserting point tile into SQLite3 database (sqlite3_step: <error_code>)"  I'm just making stuff up.  If there are any errors to anticipate along with solutions, that's always nice, but I don't know if you've got that in this case.

**Comment by mpgerlek** [comment]
@abellgithub See if you like that better... If we want to take this further, we should first define a PDAL-wide style guide for error handling, and then I'll conform to it.

(side note: I can't say things like "error inserting point" because this SQLite class is not specific to any kinds of data, e.g. points.)

**Comment by abellgithub** [comment]
I'm not sure I understand.  What else might we be storing in the DB beside points?

**Comment by mpgerlek** [comment]
Whatever you want to store... The SQLiteCommon class is a generic wrapper around sqlite3 database operations. It doesn't know anything about any kind of data or schemata.

The SQLiteReader/Writer classes use the SQLiteCommon class to work with databases containing points using a schema system Howard defined. My Rialto classes, developed later, use the SQLiteCommon class to do a sqlite database with a different schema.

**Pull request merged**
