### PR TITLE
Lasdump.hpp: fixed signed-integer-overflow undefined behavior in cksum()

### PR DESCRIPTION
**Pull request by aaronyonas**

### CODE REVIEW

**Comment by abellgithub** [comment]
I have no idea why you would be using this code. Nobody else uses it.

What is the actual issue you're concerned about?

**Comment by aaronyonas** [comment]
The undefined behavior error showed up when I ran test/unit/apps/MergeTest.cpp.
I can imagine Lasdump could be useful for debugging, but I'm not attached to it.

**Comment by aaronyonas** [comment]
The "Linux/Linux floating" and "OSX / OSX (floating)" check failures are unrelated to this PR.
```
78: [ RUN      ] FerryFilterTest.test_ferry_copy_json
78: ../test/unit/filters/FerryFilterTest.cpp:122: Failure
78: Expected equality of these values:
78:   -117.2501328350574
78:   lon
78:     Which is: -117.25014718503355
78: ../test/unit/filters/FerryFilterTest.cpp:125: Failure
78: The difference between 49.341077824192915 and lat is 6.3369252814027277e-06, which exceeds 1e-9, where
78: 49.341077824192915 evaluates to 49.341077824192915,
78: lat evaluates to 49.341084161118197, and
78: 1e-9 evaluates to 1.0000000000000001e-09.
78: [  FAILED  ] FerryFilterTest.test_ferry_copy_json (61 ms)
```
However, the "Windows / MSVC (floating)" failure looks like a real error.
```
..\io\GDALWriter.cpp(208): warning C4003: not enough arguments for function-like macro invocation 'max'
..\io\GDALWriter.cpp(208): error C2589: '(': illegal token on right side of '::'
..\io\GDALWriter.cpp(208): error C2062: type 'unknown-type' unexpected
..\io\GDALWriter.cpp(208): error C2059: syntax error: ')'
..\io\GDALWriter.cpp(210): warning C4003: not enough arguments for function-like macro invocation 'max'
..\io\GDALWriter.cpp(210): error C2589: '(': illegal token on right side of '::'
..\io\GDALWriter.cpp(210): error C2062: type 'unknown-type' unexpected
..\io\GDALWriter.cpp(210): error C2059: syntax error: ')'
```

**Comment by abellgithub** [comment]
If you merge master into this branch the issues should go away and then I'll merge it.

**Comment by abellgithub** [comment]
Fixed with 48645a94d8f74b299ff9c0eee15c6770c893f935

**Pull request closed without merging**
