### PR TITLE
tiledb: Add TileDB to CI tests

### PR DESCRIPTION
**Pull request by normanb**
Added TileDB to CI tests. Note that the Dockerfile.dependencies is failing to build the pdal/alpinebase image as `/usr/lib` is not being found for any of the dependencies (eigen, fgt cpd etc).

@abellgithub

### CODE REVIEW

**Comment by normanb** [comment]
Output for docker build

```docker build -t pdal/alpinebase -f Dockerfile.dependencies .
Sending build context to Docker daemon   16.8MB
Step 1/5 : FROM alpine:3.10
 ---> af341ccd2df8
Step 2/5 : RUN     mkdir -p /usr/include/linux;     ln -sf /usr/include/unistd.h /usr/include/linux/unistd.h
 ---> Using cache
 ---> f58eebd789d9
Step 3/5 : COPY     gdal-dev-3.0.0-r0.apk gdal-dev-3.0.0-r0.apk
 ---> Using cache
 ---> f4d06ee08001
Step 4/5 : COPY     gdal-3.0.0-r0.apk gdal-3.0.0-r0.apk
 ---> Using cache
 ---> 65cb4dd9c117
Step 5/5 : RUN     echo "@edgetesting http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories;     echo "@edgemain http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories;     apk update;     apk add --no-cache         git         cmake         ninja         g++         bash     ;     apk add --no-cache         eigen-dev         py3-numpy         py-numpy-dev         libxml2-dev         python3-dev         curl-dev         postgresql-dev         sqlite-dev         zstd-dev         bzip2-dev         openssl-dev         zlib-dev         lz4-dev         libcrypto1.1@edgemain         xerces-c@edgetesting         libspatialite-dev@edgetesting         libgeotiff-dev@edgetesting         nitro@edgetesting         nitro-dev@edgetesting         laszip-dev@edgetesting         laz-perf-dev@edgetesting         hdf5-dev@edgetesting         proj@edgetesting         proj-datumgrid@edgetesting         xerces-c@edgetesting     ;     apk add --allow-untrusted         ./gdal-dev-3.0.0-r0.apk         ./gdal-3.0.0-r0.apk;    git clone https://github.com/gadomski/fgt.git;     cd fgt;     mkdir build;     cd build;     cmake ..         -G Ninja         -DCMAKE_BUILD_TYPE=Release     ;     ninja install;     cd /;     rm -rf fgt;         git clone https://github.com/gadomski/cpd.git;     cd cpd;     mkdir build;     cd build;     cmake ..         -G Ninja         -DCMAKE_BUILD_TYPE=Release     ;     ninja install;     cd /;     rm -rf cpd;         git clone https://github.com/TileDB-Inc/TileDB.git;     cd TileDB;     git checkout 1.7.2;     mkdir build;     cd build;     cmake .. -G Ninja -DTILEDB_TBB=OFF -DTILEDB_TESTS=OFF;     ninja install;     cd /; #     rm -rf TileDB;
 ---> Running in d0cb39397926
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
v3.10.4-3-g0ed412d466 [http://dl-cdn.alpinelinux.org/alpine/v3.10/main]
v3.10.4-7-g6ee081a8fb [http://dl-cdn.alpinelinux.org/alpine/v3.10/community]
v20200122-255-gbec0b5cf37 [http://dl-cdn.alpinelinux.org/alpine/edge/testing]
v20200122-240-gd24f40bce4 [http://dl-cdn.alpinelinux.org/alpine/edge/main]
OK: 19820 distinct packages available
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
(1/34) Installing ncurses-terminfo-base (6.1_p20190518-r0)
(2/34) Installing ncurses-terminfo (6.1_p20190518-r0)
(3/34) Installing ncurses-libs (6.1_p20190518-r0)
(4/34) Installing readline (8.0.0-r0)
(5/34) Installing bash (5.0.0-r0)
Executing bash-5.0.0-r0.post-install
(6/34) Installing libacl (2.2.52-r6)
(7/34) Installing libbz2 (1.0.6-r7)
(8/34) Installing expat (2.2.8-r0)
(9/34) Installing lz4-libs (1.9.1-r0)
(10/34) Installing xz-libs (5.2.4-r0)
(11/34) Installing libarchive (3.3.3-r1)
(12/34) Installing ca-certificates (20190108-r0)
(13/34) Installing nghttp2-libs (1.39.2-r0)
(14/34) Installing libcurl (7.66.0-r0)
(15/34) Installing libgcc (8.3.0-r0)
(16/34) Installing rhash-libs (1.3.8-r0)
(17/34) Installing libstdc++ (8.3.0-r0)
(18/34) Installing libuv (1.29.1-r0)
(19/34) Installing cmake (3.14.5-r0)
(20/34) Installing cmake-bash-completion (3.14.5-r0)
(21/34) Installing binutils (2.32-r0)
(22/34) Installing gmp (6.1.2-r1)
(23/34) Installing isl (0.18-r0)
(24/34) Installing libgomp (8.3.0-r0)
(25/34) Installing libatomic (8.3.0-r0)
(26/34) Installing mpfr3 (3.1.5-r1)
(27/34) Installing mpc1 (1.1.0-r0)
(28/34) Installing gcc (8.3.0-r0)
(29/34) Installing musl-dev (1.1.22-r3)
(30/34) Installing libc-dev (0.7.1-r0)
(31/34) Installing g++ (8.3.0-r0)
(32/34) Installing pcre2 (10.33-r0)
(33/34) Installing git (2.22.2-r0)
(34/34) Installing ninja (1.9.0-r1)
Executing busybox-1.30.1-r3.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 210 MiB in 48 packages
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  proj (missing):
    required by: world[proj]
  proj-datumgrid (missing):
    required by: world[proj-datumgrid]
  xerces-c (missing):
    required by: world[xerces-c]
  so:libproj.so.15 (missing):
    required by: libgeotiff-1.5.1-r3[so:libproj.so.15]
                 libspatialite-4.3.0a-r6[so:libproj.so.15]
  so:libgeos_c.so.1 (missing):
    required by: libspatialite-4.3.0a-r6[so:libgeos_c.so.1]
ERROR: unsatisfiable constraints:
  libgeotiff-1.5.1-r3:
    masked in: @edgetesting
    satisfies: gdal-3.0.0-r0[so:libgeotiff.so.5]
  so:libproj.so.15 (missing):
    required by: libgeotiff-1.5.1-r3[so:libproj.so.15]
                 gdal-3.0.0-r0[so:libproj.so.15]
  hdf5-1.10.6-r0:
    masked in: @edgetesting
    satisfies: gdal-3.0.0-r0[so:libhdf5.so.103]
  so:libgeos_c.so.1 (missing):
    required by: gdal-3.0.0-r0[so:libgeos_c.so.1]
  so:libxerces-c-3.2.so (missing):
    required by: gdal-3.0.0-r0[so:libxerces-c-3.2.so]
Cloning into 'fgt'...
-- The CXX compiler identification is GNU 8.3.0
-- The C compiler identification is GNU 8.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- [fgt] Compiler: GNU
-- [fgt] Version: 0.4.6
-- [fgt] With OpenMP: OFF
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK)
  (Required is at least version "3.1")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindEigen3.cmake:76 (find_package_handle_standard_args)
  CMakeLists.txt:44 (find_package)


-- Configuring incomplete, errors occurred!
See also "/fgt/build/CMakeFiles/CMakeOutput.log".
ninja: error: loading 'build.ninja': No such file or directory
Cloning into 'cpd'...
-- The CXX compiler identification is GNU 8.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK)
  (Required is at least version "2.91.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindEigen3.cmake:76 (find_package_handle_standard_args)
  CMakeLists.txt:26 (find_package)


-- Configuring incomplete, errors occurred!
See also "/cpd/build/CMakeFiles/CMakeOutput.log".
```

**Comment by abellgithub** [comment]
Sorry to be so long on this...

I'm building TileDB against Alpine 3.11.  Seems fine but it says there's no install target:

```
...
Cloning into 'TileDB'...
Note: switching to '1.7.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 3fa6756a Update HISTORY for 1.7.2
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Starting TileDB superbuild.
-- Found Bzip2: /usr/lib/libbz2.so
-- Found LZ4: /usr/lib/liblz4.so
-- Found Spdlog: /usr/include
-- Found Zlib: /lib/libz.so
-- Found Zstd: /usr/lib/libzstd.so
-- Found OpenSSL: /usr/lib/libssl.so -- OpenSSL crypto: /usr/lib/libcrypto.so -- root: /TileDB/build/externals/install;/usr/local/opt/openssl
-- Not found clang-tidy
-- Not found clang-format
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Install prefix is /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /TileDB/build
ninja: error: unknown target 'install'
Removing intermediate container 6e77c643243d
 ---> 7304677f620f
Successfully built 7304677f620f
```

**Comment by normanb** [comment]
@abellgithub do you have an updated dockerfile that I can look at?

**Comment by abellgithub** [comment]
They're checked into the master branch: 

https://github.com/PDAL/PDAL/tree/master/scripts/docker/alpine

The results I posted are from pasting the changes from this PR into `Dockerfile.master`.

**Comment by normanb** [comment]
I have rebased master on to this branch and I can recreate the `ninja: error: unknown target 'install'`. I will debug and update this PR

**Comment by normanb** [comment]
@abellgithub this fixes the issue with `ninja install`

**Comment by abellgithub** [comment]
@normanb : I can't get this to work with either target:

```

**Comment by abellgithub** [comment]
When I install, the base location is incorrect.  It sticks them in a directory called `build`:

```
Install the project...
-- Install configuration: "Release"
-- Installing: /build/usr/local/lib/libtiledb.so.1.7
-- Set runtime path of "/build/usr/local/lib/libtiledb.so.1.7" to "/usr/local/lib"
-- Installing: /build/usr/local/lib/libtiledb.so
-- Installing: /build/usr/local/include/tiledb/tiledb.h
-- Installing: /build/usr/local/include/tiledb/tiledb_enum.h
-- Installing: /build/usr/local/include/tiledb/tiledb_version.h
-- Installing: /build/usr/local/include/tiledb/tiledb
-- Installing: /build/usr/local/include/tiledb/array.h
...
```

**Comment by hobu** [comment]
You also need to install them manually into DESTDIR=/ because of the way that Dockerfile is configured. See some of the other recipes above it for examples.

**Comment by normanb** [comment]
I will get to fixing this but can be after 2.1 imo

**Comment by abellgithub** [comment]
There's nothing to fix. I have this working in master. I think this can be
closed.

**Pull request closed without merging**
