### PR TITLE
LasHeader copyable

### PR DESCRIPTION
**Pull request by jjimenezshaw**
This PR fixes the issue described in #4008

The changes in the code try to be minimal.

The idea is to move the ownership of `las::Header`, `las::Srs`, `las::VlrList` from `LasReader` to `LasHeader`. Because `LasReader` will always have the internal instance of `LasHeader`, the references are never pointing to invalid data.

### CODE REVIEW

**Comment by jjimenezshaw** [comment]
The constructor `LasHeader(las::Header& h, las::Srs& srs, las::VlrList& vlrs);` is not used now in the code of PDAL (I do not know if it makes sense for external users). Should I remove it?

**Comment by abellgithub** [comment]
This is essentially API-breaking as sets to the header will no longer update the reader, and gets will no longer be guaranteed to get current data (depending on use).

**Comment by jjimenezshaw** [comment]
Well, that is the issue we are addressing here. In C++, if I make a _copy_ of a variable returned by reference, I do not expect that changes there affect the original object. If I want that I would make a reference, not a copy.

**Comment by abellgithub** [comment]
You're just expecting the object to contain all the header data. It does
not. It provides an API to the data.

**Comment by hobu** [comment]
@jjimenezshaw what if we were to go forward and finish deprecating and removing LasHeader and friends? Part of the problem is we didn't give enough time for a transition and we slapped it back in the codebase. We would much rather have code using the (newer, better) API.

**Comment by jjimenezshaw** [comment]
> deprecating and removing LasHeader and friends

No problem. This PR was to solve a bug in the management of the data, that could happen to a user without noticing it (that happened to us. We were lucky and a unit test failed, but could not fail as well). I do not have special interest on keeping LasHeader.

**Comment by hobu** [comment]
>We were lucky and a unit test failed 

Does that mean you are currently using LasHeader and friends in your software and would have to migrate to the newer api?

**Comment by jjimenezshaw** [comment]
> Does that mean you are currently using LasHeader and friends in your software and would have to migrate to the newer api?

Yes, we are using it to get the bbox, wkt, pointCount and las version. We are doing it in a couple of places, so changing it should be easy. Not a problem.

**Comment by hobu** [comment]
Ok, I'll close this. The next person coming along should see they should use the other non-deprecated API. It appears that both LasHeader.hpp and LasVLR.hpp are decorated as `[[deprecated]]` in master, so I don't think there's more to do here other that to add more to the release notes that it will be removed in 2.7.

**Comment by loreilei** [comment]
Hi @hobu , I am a colleague of @jjimenezshaw.

Sorry for jumping in the topic LasHeader deprecation topic. I am not against it, as said before we can adapt to the new API.

I was just wondering what is the new API to read the information mentioned by @jjimenezshaw ? (bbox, wkt, point count, las version).

I saw there is a `las::Header` struct that is private the `LasReader`, and a public `LasHeader` accessor which will be deprecated if I understood correctly the previous conversation. If that understanding is correct, what is the API to read the header information?

Thanks in advance for your answers.

**Comment by hobu** [comment]
I think the intention was to make `las::Header` and friends public. Is that correct @abellgithub ?

**Comment by abellgithub** [comment]
No. `las::Header` is an implementation detail. It allows an internal representation of the data that does not map exactly to the bytes in the file. I left the old LasHeader API to allow for backward-compatible data access, but it's not a structure that you can pass around. It's an interface, if you will.

See this comment: https://github.com/PDAL/PDAL/issues/4008#issuecomment-1480305306

If a user wants a LAS header as raw bytes, it's very easy to read the first 227/235/375 bytes of the file. You can also use the lazperf code to easily read the file header:
```
ifstream in("filename.las");
lazperf::reader::basic_file f;
f.open(in);
lazperf::header14 h = f.header();
```

You can use this whether your file is 1.4 or not, just don't try to access fields that aren't part of the header of the actual file version as they will be uninitialized.

**Comment by jjimenezshaw** [comment]
> to get the bbox, wkt, pointCount and las version.

How can we get this four parameters from a `LasReader` (without reading the whole file)?

**Comment by hobu** [comment]
[`Stage::preview()`](https://github.com/PDAL/PDAL/blob/master/pdal/Stage.hpp#L115) is what you should use to get a `MetadataNode` with that info in it for drivers that support the method. `readers.las` provides this, but `readers.copc` does not. We should probably add that to enable streaming of header info over the network.

**Comment by abellgithub** [comment]
I don't understand the issue. You can use the provided `LasHeader`. As Howard said, you can also call `preview()` and extract the information via. metadata. You can also use the technique I provided above. It's 4 lines of code.

**Pull request closed without merging**
