### PR TITLE
Fixes memory leaks found when runing ctest

### PR DESCRIPTION
**Pull request by rouault**
Found with a -fsanitize=address build

### CODE REVIEW

**Comment by rouault** [comment]
Even if the fixes don't seem important for production use, they are a precondition if one day you want to run ctest on a ASAN enabled build (which would be a good engineering practice IMHO).
I'm not sure which exception should be caught exactly in the stream reading part ?

**Comment by abellgithub** [comment]
I've run ASAN on things at times.  I guess I don't get too shook if it reports errors that I understand.

I'll merge this and go back and try to handle the wildcard exceptions so that it's clear in the code what the failure might be.

**Comment by rouault** [comment]
>  I guess I don't get too shook if it reports errors that I understand.

my point was to enable it on CI, so that pull requests get tested for correctness. In such setup, you want everything reported to have been fixed.

**Comment by abellgithub** [comment]
Yes, I understand.  I'm not sure that I agree with the principle.  I've spent many weeks of my life satisfying lint-type systems for no real benefit and more obtuse code.  (Casts that change no behavior but quiet the compiler are, to me, particularly annoying, and I think a net harm.)

But sometimes such tools find important issues.  I'm not sure what the best solution is.

Thanks for taking the time.  I'm not sure that I'm pleased or disappointed that you didn't find something more interesting.

**Pull request merged**
