### PR TITLE
Basic support for e57 format

### PR DESCRIPTION
**Pull request by nicolas-chaulet**
This PR provides very basic e57 support, it is not meant to be comprehensive but provides enough support for getting some data in and out of e57. A few things to notice:

- this is mainly a wrapper around the core e57 format library implementation there:
https://github.com/asmaloney/libE57Format 
- The libE57Format code was copied over into the `plugins/e57/libE57Format` folder
- The libE57Format library relies on [xerces-c](https://xerces.apache.org/xerces-c/) for xml io

Things that remain to be done:

- Document the plugin (will do once the core principles are agreed)
- Integrate with the CI and CD pipelines, I will need some guidance there, like what is the docker image that needs to be updated to run travis CI?

Please let me know what you think, I'll be happy to review and update.

### CODE REVIEW

**Comment by abellgithub** [comment]
There's quite a lot here so it may take me a little while to review.

This is much appreciated.

**Comment by nicolas-chaulet** [comment]
I can appreciate that. Most of the code is actually the libE57Format library which is tracked here: https://github.com/asmaloney/libE57Format so probably not in the scope of this PR.

**Comment by hobu** [comment]
Can you allow [commits from maintainers](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) on this one?

**Comment by nicolas-chaulet** [comment]
> Can you allow [commits from maintainers](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) on this one?

It should be already on.

**Comment by hobu** [comment]
We're exploring switching the e57 code to use libxml2 instead of xerces because PDAL is already using libxml2 in a few other contexts. 

Also, we needed to make a xerces package for Alpine to get the Travis builds working. Those are the things holding up the merge at this point.

**Comment by hobu** [comment]
The activity on this PR has moved to #2486.

**Pull request closed without merging**
