### PR TITLE
Add outlier detection criterion and make minor edit to filters.lof documentation

### PR DESCRIPTION
**Pull request by chambbj**
This commit adds three filters that are implementations of the outlier
detection criterion specified in Weyrich, T et al. “Post-Processing of Scanned
3D Surface Data.” Proceedings of Eurographics Symposium on Point-Based Graphics
2004 (2004): 85–94. Print.

* Nearest-Neighbor Reciprocity Criterion available as filters.reciprocity

* Miniball Criterion available as filters.miniball

* Plane Fit Criterion available as filters.planefit

### CODE REVIEW

**Comment by hobu** [comment]
```c:\projects\pdal\filters\private\miniball\Seb_debug.h(12): fatal error C1083: Cannot open include file: 'sys/resource.h': No```

**Comment by chambbj** [comment]
Boo. Guess I didn't look closely at possible issues with Windows.

**Comment by abellgithub** [comment]
@chambbj : Where is this?  It's unclear to me that you're happy with this.

**Comment by chambbj** [comment]
I just restarted the Appveyor builds to see if we get a green light. I'm fine otherwise.

**Comment by abellgithub** [comment]
@chambbj - This is still showing failing.

**Comment by chambbj** [comment]
Thanks for reminding me @abellgithub. Probably just needed to catch up to our treatment of Eigen matrices as doubles.

**Comment by chambbj** [comment]
And green lights once again. Shall we merge @abellgithub?

**Comment by abellgithub** [comment]
There are tests for reciprocity, but not miniball or plane fit.  Should there be?

**Comment by chambbj** [comment]
Oh, I suppose there should be 😝. I've not written any.

**Comment by abellgithub** [comment]
I'd be happy to do it if I knew expected behavior.  If you had something you could point me to on this...

**Comment by chambbj** [comment]
Yeah, so both are documented on page 5 of
> Weyrich, T et al. “Post-Processing of Scanned 3D Surface Data.” Proceedings of Eurographics Symposium on Point-Based Graphics 2004 (2004): 85–94. Print.

**Pull request merged**
