### PR TITLE
updating arbiter

### PR DESCRIPTION
**Pull request by mccarthyryanc**
Updating arbiter. I wasn't sure if there was an official release schedule with arbiter, so I figured I'd try a PR and see where that went!

I followed the amalgamate instructions from the readme.

### CODE REVIEW

**Comment by connormanning** [comment]
Thanks for this.  A couple of notes:
- The readme in `vendor/arbiter` is inaccurate, the `-j` flag should be removed from the amalgamate invocation (this is why your header file has a massive diff)
- I just upstreamed another change from PDAL up to arbiter - a constructor was missing in Arbiter that was added directly to PDAL's bundle

I've fixed the arbiter readme and re-bundled with this change on branch `arbiter-update` - can you merge this into your fork @mccarthyryanc ?

And for @abellgithub's benefit, the changes included here are:
- Support for case-insensitive HTTP header searching has been upstreamed
- AWS Fargate support added
- AWS session token support added (contributed by @mccarthyryanc)
- `getBasename` fixed for Windows paths (was only looking for the unix separator)

**Comment by mccarthyryanc** [comment]
@connormanning and @abellgithub, I merged in those commits (thanks for the correction, I was a little suspicious about the large diff but I figured y'all would know what was going on :wink: ). Let me know if there is anything else I can do!

**Comment by mccarthyryanc** [comment]
@connormanning and @abellgithub , looks like one check didn't pass. Is there anything I can help with for a fix to get this PR merged?

**Comment by abellgithub** [comment]
I have to look into why things aren't running on OSX.

**Pull request merged**
