### PR TITLE
Arbiter S3 IMDS fallback v2->v1

### PR DESCRIPTION
**Pull request by connormanning**
Fall back to IMDSv1 if v2 fails.  Remove exponential backoff/retry loop for these queries (which is most of the diff here).

### CODE REVIEW

**Comment by msmitherdc** [comment]
It does fallback, but it takes a while with multiple timeouts to do so
`
pdal info s3://grid-dev-publiclidar/nato/slovenia/copc/TM_374_130.copc.laz --verbose=8
(PDAL Debug) Debugging...
Curl failure: Timeout was reached
Curl failure: Timeout was reached
(pdal info Debug) Executing pipeline in stream mode.
Curl failure: Timeout was reached
Curl failure: Timeout was reached
{
  "file_size": 123637865,
  "filename": "s3://grid-dev-publiclidar/nato/slovenia/copc/TM_374_130.copc.laz",
  "now": "2023-06-03T16:30:54+0000",
  "pdal_version": "2.6.0 (git-version: a0141a)",
  "reader": "readers.copc",
`

**Comment by msmitherdc** [comment]
for `time pdal info --metadata s3://grid-dev-publiclidar/nato/slovenia/copc/TM_374_130.copc.laz --verbose=8`

v2: `real	0m0.319s`
v1:  `real	0m5.126s`

**Comment by connormanning** [comment]
Yeah that's about expected with the current code - I can get that quite a bit lower with a few small tweaks but there is always going to be a bit of a timeout for this fallback.  I just pushed a few tweaks that should lower it to about a second, and there is a bit more that can be done to get it down to an explicitly configured timeout of, say, 100ms.

**Comment by hobu** [comment]
Picked back to `2.5-maintenance` at 751a64bcea9475e013a0293d941f9aa897ef0779

**Pull request merged**
