### PR TITLE
Remove pgpointcloud GHT compression

### PR DESCRIPTION
**Pull request by elemoine**
Remove pgpointcloud GHT compression, as the support for GHT compression has been removed in pgpointcloud v1.2.0. See https://github.com/pgpointcloud/pointcloud/pull/214.

### CODE REVIEW

**Comment by elemoine** [comment]
> I can't imagine it matters, but we should probably leave the values of the CompressionType the same since they were specified explicitly.

Yes, I was hesitating. And don't we think we should keep the Ght compression type in the enum class? It would be weird to have this:

```c++
enum class CompressionType
{
    None = 0,
    Dimensional = 2,
    Lazperf = 3,
    Unknown = 256
}
```

The absence of value `1` would be hard to to understand, if even possible.

**Comment by elemoine** [comment]
I've added `Ght` back to the `CompressionType` enum class.

**Comment by abellgithub** [comment]
I'd probably do something like:

```c++
enum class CompressionType
{
    None = 0,
//  Ght = 1,   -- Removed compression type
    Dimensional = 2,
    Lazperf = 3,
    Unknown = 256
}
```

**Comment by elemoine** [comment]
Works for me too. Done.

**Comment by abellgithub** [comment]
Thanks so much!

**Comment by abellgithub** [comment]
Close #2148

**Pull request merged**
