### PR TITLE
added missing Options::remove() for #915

### PR DESCRIPTION
**Pull request by mpgerlek**

### CODE REVIEW

**Comment by abellgithub** [comment]
Do we need this?  Can't one just fetch the existing option by reference and reset the value?

**Comment by mpgerlek** [comment]
Is there a fetch-by-ref? I had looked, but did not see one --but then I saw that there was a remove() already declared in there so I decided to happily just use that.

**Comment by mpgerlek** [comment]
(If there is a fetch-by-ref, /me will change this PR to delete the remove() declaration.)

**Comment by hobu** [comment]
Is this one dead?

**Comment by mpgerlek** [comment]
No, it's still a thing.

.mpg

On Jun 7, 2015, at 11:28 AM, Howard Butler <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this one dead?

**Comment by abellgithub** [comment]
I thought it was unnecessary given the usage.  I don't think anyone calls it.

**Comment by abellgithub** [comment]
Handled elsewhere.

**Pull request closed without merging**
