### PR TITLE
Fix case where endpoint lies exactly on a grid intersection.

### PR DESCRIPTION
**Pull request by abellgithub**
@hobu: Can you please tests some crop stuff with this change?

### CODE REVIEW

**Comment by hobu** [comment]
Successfully works for me.

Test case attached.

[issue-3956.zip](https://github.com/PDAL/PDAL/files/10528482/issue-3956.zip)

**Comment by hobu** [comment]
Picked back to `2.5-maintenance` at 521680e7b1f6a06e8a049fa7e977cda0e286b0b4

**Comment by CharlesGaydon** [comment]
> Picked back to `2.5-maintenance` at [521680e](https://github.com/PDAL/PDAL/commit/521680e7b1f6a06e8a049fa7e977cda0e286b0b4)

I understand that this means the conda package for V2.5.0 will be updated, without a need for users to update dependencies? I observe that [an error in the conda build for `2.5-maintenance`](https://github.com/PDAL/PDAL/actions/runs/4047102593/jobs/6960713903) (you've probably seen it, sorry to be redundant if this is the case).

**Comment by hobu** [comment]
it will be included in PDAL 2.5.1 when that is released, which is expected in the next week or two.

**Pull request merged**
