### PR TITLE
Add kernel to compute Hausdorff distance between two point clouds

### PR DESCRIPTION
**Pull request by chambbj**
Just provides a measure of similarity between point clouds.

https://en.wikipedia.org/wiki/Hausdorff_distance

### CODE REVIEW

**Comment by abellgithub** [comment]
Tests?

**Comment by hobu** [comment]
This can't be used from pipelines, right? Is there a scenario where it could be? Seems like more of a utility function than a filter because of that...

**Comment by chambbj** [comment]
Well I've got it coded as a kernel not a filter anyway. I did start to pull
it out as a utility function to make it easier to test per Andrew's
comment, but I had no plans to use in a pipeline regardless, I'd just call
that distance function from the kernel.

**Comment by hobu** [comment]
d'oh. I didn't even read :)

**Comment by chambbj** [comment]
@abellgithub Tests added.

**Pull request merged**
