### PR TITLE
Add note to docs about pgpointcloud tests

### PR DESCRIPTION
**Pull request by elemoine**
This adds a note to the testing doc page on how to run the pgpointcloud tests.

### CODE REVIEW

**Comment by elemoine** [comment]
The docs on pdal.io is for the current release (1.5.0). Is the "master" version of the docs available online? Thanks.

**Comment by hobu** [comment]
> Is the "master" version of the docs available online?

No, doc updates like this need to be cherry-picked back to the `1.5-maintenance` branch if we want a website refresh. I'll take care of that now.

**Comment by elemoine** [comment]
Thanks for the answer @hobu. I was just curious about that.

**Comment by elemoine** [comment]
Oops, your cherry-pick revealed an RST formatting issue in the note i added. I am sorry about that. I'll fix it.

https://www.pdal.io/development/testing.html

**Comment by elemoine** [comment]
See https://github.com/PDAL/PDAL/pull/1574. Sorry again. I checked it locally this time.

**Pull request merged**
