### PR TITLE
Ignore points indicated by classbit, do not toss them. Add documentation.

### PR DESCRIPTION
**Pull request by chambbj**

### CODE REVIEW

**Comment by abellgithub** [comment]
Should this functionality be in PMF as well?

**Comment by chambbj** [comment]
@abellgithub It could, sure. But you could arguably want to use it in many filters, and I don't know where to draw the line. This at least fixes the one place where it was already used. I think for other instances it may be better to wait for named PointViews (or whatever we plan to do).

**Comment by abellgithub** [comment]
That's fine.  There just tends to be a parallel in what's in SMRF and PMF.

**Comment by AzarArgh** [comment]
Hi, I had a hard time installing PDAL in windows 10. Fortunately, after I read your comments in 'Issue with packages python-pdal and pdal #57' and tried 
conda create -n pdal-env -c conda-forge python-pdal pdal 
conda activate pdal-env
it worked with no error in anaconda prompt. But how can I work and import PDAL in for example spyder? I tried it  still hasn't work. Thank you so much.

**Comment by chambbj** [comment]
@AzarArgh Be aware that this out of place question is very likely to get ignored, as it being posted in a closed pull request and is completely unrelated. How-to questions are better suited for the mailing list and if you have actually getting some sort of error, you are advised to create a new GitHub issue with sufficient information for someone to be able to actually recreate/diagnose.

**Comment by AzarArgh** [comment]
Thank you, I am new in GitHub because of that I haven't noticed. I will follow.

**Pull request merged**
