### PR TITLE
Warnings cleanup

### PR DESCRIPTION
**Pull request by hobu**

### CODE REVIEW

**Comment by hobu** [comment]
Implemented #2341

**Comment by abellgithub** [comment]
The changes in Metadata seem like some leftover stuff from another project.

**Comment by hobu** [comment]
`std::stod`  in C++17 now pitches this warning on Windows: 
> discarding return value of function with 'nodiscard' attribute

**Comment by abellgithub** [comment]
Usually you just do (void)func(...) to get around that.

**Comment by hobu** [comment]
Picked back to `2.5-maintenance` branch at 870b50b5e017ae3c02dc9a762e450029f15a78a8

**Pull request merged**
