### PR TITLE
SparseMatrix: __pragma is msvc-specific

### PR DESCRIPTION
**Pull request by xantares**
we want to use the gnu variant on mingw

### CODE REVIEW

**Review by hobu — APPROVED** [review]
This should be upstreamed to kazhdan, but our experience is he doesn't merge stuff.

**Comment by abellgithub** [comment]
There is usually a compiler option to ignore unknown pragmas. That should be used instead of this confusing stuff.

**Comment by xantares** [comment]
we dont want to ignore omp pragmas

**Comment by abellgithub** [comment]
Fixed by #3533

**Pull request closed without merging**
