### PR TITLE
Add passthrough filter

### PR DESCRIPTION
**Pull request by chambbj**
This could obviously be more complicated, but as it is, I think it's a nice
alternative to the Python filters. The documentation, sample pipeline, and unit
tests should adequately explain the current feature set (basically
multi-dimensional, min/max/exact value criteria for passing points through to
the output buffer).

### CODE REVIEW

**Comment by chambbj** [comment]
Just to clarify, this is not intended to be a full replacement for Python, just a small subset for simple filtering.

**Comment by hobu** [comment]
Could this be called `filters.sieve`?

**Comment by chambbj** [comment]
I have no strong feeling on the name. Passthrough is just the analogue in PCL.

**Comment by hobu** [comment]
ah, that's fine to keep it aligned then. I think our challenge is that `filters` itself is probably wrong, since they don't really/always "filter".

**Comment by chambbj** [comment]
I still have it in the back of my head to possible split the filters from the non-filters. I struggle a little with what to call the non-filters. I believe @abellgithub processed "operations" or something similar.

**Comment by gadomski** [comment]
My two cents: `sieve` does make more sense than `passthrough` for me — I had to go look at the source to figure out what `passthrough` did, but I think I could have intuited `sieve`.

**Comment by chambbj** [comment]
Discussed offline -- this basically just filters a range, and we don't have plans to make it any more complicated than that, so call it a range filter.

**Comment by chambbj** [comment]
I'd missed a file rename on this. Otherwise, assuming it passes Travis, it's all ready to go.

**Pull request merged**
