### PR TITLE
OpenSSL support

### PR DESCRIPTION
**Pull request by nicolas-chaulet**
Let's see if forcing version 1.1 fixes the issues we were having

### CODE REVIEW

**Comment by nicolas-chaulet** [comment]
I don't have a windows machine at my disposal and are really unexperienced with it. The current version of PDAL does not support openssl at all, so I thought it would still be an improvement to have support for Unix systems.

**Comment by hobu** [comment]
https://ci.appveyor.com/project/hobu/pdal/builds/23448344/job/7po35sdjh6mlyfhk#L932 would imply that pdal_arbiter.lib needs to link against something more.

**Comment by nicolas-chaulet** [comment]
Yes, this time it's my bad, I forgot to deactivate openssl support in arbiter. The first commit gave the following:
https://ci.appveyor.com/project/hobu/pdal/builds/23448344/job/7po35sdjh6mlyfhk
which suggests that it tries to link against openssl1.0 (as opposed to 1.1) despite properly detecting openssl1.1 at configure time.

**Comment by hobu** [comment]
Moved this to #2436 to include windows support.

**Pull request closed without merging**
