### PR TITLE
update nanoflann to recent code

### PR DESCRIPTION
**Pull request by hobu**

### CODE REVIEW

**Comment by abellgithub** [comment]
Why?

There is a lot of cruft that was added to nanoflann. I was watching their commits and integrating anything that mattered, but of course I'm no longer doing that.

**Comment by hobu** [comment]
Just testing to see if there are any significant performance wins to get.

**Comment by hobu** [comment]
# New nanoflann

time ./bin/pdal translate ../../pdal-data/autzen/autzen-classified.copc.laz junk.las --filter smrf
./bin/pdal translate ../../pdal-data/autzen/autzen-classified.copc.laz   smrf  77.54s user 2.53s system 105% cpu 1:15.86 total

time ./bin/pdal translate ../../pdal-data/autzen/autzen-classified.copc.laz junk.las --filter smrf
./bin/pdal translate ../../pdal-data/autzen/autzen-classified.copc.laz   smrf  77.02s user 2.19s system 105% cpu 1:14.92 total


# Old nanoflann

```
time ./bin/pdal translate ../../pdal-data/autzen/autzen-classified.copc.laz junk.las --filter smrf
./bin/pdal translate ../../pdal-data/autzen/autzen-classified.copc.laz   smrf  67.26s user 2.41s system 105% cpu 1:05.73 total
```

# New nanoflann

```
time ./bin/pdal translate ../../pdal-data/autzen/autzen-classified.copc.laz junk.las --filter smrf
./bin/pdal translate ../../pdal-data/autzen/autzen-classified.copc.laz   smrf  66.57s user 2.27s system 106% cpu 1:04.68 total
```

**Comment by hobu** [comment]
Our current implementation is significantly faster for now. Closing this PR and branch.

**Pull request closed without merging**
