### PR TITLE
remove Utils::hexDump which is not used and causes compilation securi…

### PR DESCRIPTION
**Pull request by hobu**
…ty warnings

### CODE REVIEW

**Comment by hobu** [comment]
This isn't used anywhere in PDAL. If someone wants to replace it with something else https://github.com/zmb3/hexdump might be a decent update.

**Comment by abellgithub** [comment]
This is just a useful debugging tool that one can call when necessary in a test/development environment.

Would be curious to know about the security warnings.

**Comment by hobu** [comment]
```
/Users/hobu/miniforge3/envs/conda-build/conda-bld/pdal-split_1692911416302/work/pdal/util/Utils.cpp:621:7: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
      sprintf(foo, "0x%06x ", address);
      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
/Users/hobu/miniforge3/envs/conda-build/conda-bld/pdal-split_1692911416302/work/pdal/util/Utils.cpp:625:13: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
            sprintf(foo, "%02X ", cp[i]);
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
/Users/hobu/miniforge3/envs/conda-build/conda-bld/pdal-split_1692911416302/work/pdal/util/Utils.cpp:633:10: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
         sprintf(foo, "%c", isprint(cp[i]) ? cp[i] : '.');
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
```

I think MSVC complains about sprintf now too but we probably have the warnings turned off for it.

**Comment by abellgithub** [comment]
Oh my. The code I'm working on now wouldn't know what to do without sprint.

**Pull request merged**
