### PR TITLE
Make Poisson sampling streamable

### PR DESCRIPTION
**Pull request by chambbj**
Still want to understand an artifact that I don't quite understand, but this is otherwise ready for review.

### CODE REVIEW

**Review by nicolas-chaulet — COMMENTED** [review]
If I understand correctly, you maintain a set of occupied voxels that is growing linearly with the amount of data that you keep in the output point cloud. We had the same situation with the voxel filter that was turned into a semi streamable version. It might be worth mentioning that in the doc to avoid misunderstanding and people getting confused because the memory footprint of this stage could be quite large despite being streamable.

**Comment by chambbj** [comment]
That is correct. The occupied voxels will grow as the space covered by the point cloud is enlarged while iterating. For massive datasets (or very small voxel size!), this could be quite a large memory footprint. I'll see if I can come up with some language to convey this.

**Comment by abellgithub** [comment]
@chambbj : Can you please merge master into this if you still want the change merged? Thx.

**Comment by chambbj** [comment]
Just rebased and squashed for a much cleaner commit @abellgithub

**Pull request merged**
