### PR TITLE
Show if stage is streamable in pdal --options

### PR DESCRIPTION
**Pull request by tmontaigu**
Add the code to ouput wether a stage supports streaming in `pdal --options`. (#2480)
I did not change the outputed json by the `--showjson` switch.

And i'm not too sure about the placement of the text as it could look like an option 

streamable

### CODE REVIEW

**Comment by abellgithub** [comment]
I agree that the placement could be confusing.  How about:

```
filters.whatever
Streamable: [yes/no]
Documentations: http://pdal.io/stages/filters.whatever.html
------------------------------------------------------------
```

**Comment by hobu** [comment]
As long as it continues to be valid reStructured text so it can be conveniently be piped to HTML/PDF, I don't care.

**Comment by abellgithub** [comment]
Would you be interested in moving this function to `pdal --drivers --showjson` instead of `pdal --options`?  See #2573

**Comment by hobu** [comment]
That would be fine.

**Comment by hobu** [comment]
Did this get merged? If so, which variant got merged?

**Pull request closed without merging**
