### PR TITLE
fix linker error: add reference to re2

### PR DESCRIPTION
**Pull request by t0b3**
Closes: https://github.com/PDAL/PDAL/issues/3944

### CODE REVIEW

**Comment by abellgithub** [comment]
There isn't a good reason why this would have to be explicitly linked, and it certainly isn't something to link on 99% of systems.

**Comment by t0b3** [comment]
@abellgithub I don't mind how you fix this. As long as you come up with another useful solution which applies to gentoo ebuild we are all happy, see https://github.com/gentoo/gentoo/tree/master/sci-libs/pdal :+1:

**Comment by abellgithub** [comment]
You're welcome to do whatever you need locally to fix your issue, of course, but you'll have to figure out the detailed reason for the problem before you can expect anyone to address it in the repository.

**Comment by hobu** [comment]
It came from abseil, which now seems to require it. We should turn off abseil unless explicitly asked for so as to not drag this stuff in. 

Additionally, the 2.5.0 release hid all symbols that were not explicitly  exported. This might have some side effects.

**Comment by abellgithub** [comment]
If it were a true dependency, there should be an entry in the linked library that references it and it should be automatically linked. It doesn't make sense that optimization is happening with a debug build. I would call that an unsupported configuration, though this may not be the issue at hand. I would ask what's different about this system/configuration.

**Comment by hobu** [comment]
The re2 requirement came from https://github.com/PDAL/PDAL/commit/366aa8442db3b5036fbe95ab019231a32c7c3777

The newer version of abseil I was running locally required it but I didn't account for the fact that older versions didn't. Something must not be quite right about older versions' cmake configuration as to automatically bring re2 or not as needed.

I think we should switch abseil to an explicitly opt-on option. It's really just for developer scenarios.

**Comment by hobu** [comment]
>I think we should switch abseil to an explicitly opt-on option. It's really just for developer scenarios.

Done in #3948

**Pull request closed without merging**
