### PR TITLE
Streamable iterator

### PR DESCRIPTION
**Pull request by gsakkis**
This PR adds `PipelineStreamableExecutor` and `StreamableIterator` classes to enable streamable execution in PDAL Python (related PR coming soon). The `Streamable` and `PipelineExecutor` classes were also refactored extensively, along with a few minor necessary changes to `PipelineManager` and `PointView`.

### CODE REVIEW

**Comment by abellgithub** [comment]
This is what I was trying to discuss and perhaps we had a disconnect. I'm hesitant to modify the Streamable/Stage interfaces without good reason and understanding the intent. What are we trying to achieve with these changes, exactly?

**Comment by gsakkis** [comment]
> This is what I was trying to discuss and perhaps we had a disconnect. I'm hesitant to modify the Streamable/Stage interfaces without good reason and understanding the intent. 

There is no change in the Streamable/Stage interfaces; all tests are passing (except for 2 unrelated failures also [failing on master](https://github.com/PDAL/PDAL/issues/3555)).

> What are we trying to achieve with these changes, exactly?

Running streamable pipelines from Python in streaming mode (i.e. prevent running out of memory), coupled with a Pythonic [iterator API](https://github.com/TileDB-Inc/python/tree/PipelineIterator#iterator-api). More examples/tests [here](https://github.com/TileDB-Inc/python/blob/PipelineIterator/test/test_pipeline.py#L203).

**Comment by gsakkis** [comment]
> Maybe I'm missing something but I think this can be done without changing any PDAL code by adding a stage to extract the data at the end of the pipeline. 

I'm not quite sure what you're proposing. Do you mean without changing the PDAL `Streamable` code and adding something like a `writers.numpy_memoryview` plugin instead?

> When all points in the point table have been processed, clear() is called, which provides a hook to do any processing you would want to do in Python.

`clear()` is a Table method, not a `Stage` method; did you mean `done()`? Either way this is called by `Streamable::execute()` deep inside a loop. How would I yield back to Python the current filled NDArray while `Streamable::execute()` is still in progress?

**Comment by abellgithub** [comment]
> I'm not quite sure what you're proposing. Do you mean without changing the PDAL Streamable code and adding something like a writers.numpy_memoryview plugin instead?

Pretty much, yes.

After I wrote last night I couldn't really see a reason why we couldn't just create a StreamPointTable that was backed by an NDArray and avoid the copying altogether when working in stream mode.

But even with this see two things missing that weren't really anticipated:

1) Allow a user to pass a table into the PipelineManager. I think this is a simple change.
2) Provide some interruption when `clear()` is called. It seems to beg for coroutines in this use case (first time I've ever seen a real use for coroutines in practice), but we could do this by executing PDAL in a thread. It would be even more slick to yield the active NDArray to Python while you continue processing with PDAL with another NDArray, but this may be too much.

Maybe some combination of this stuff with what you've done would work? I would love to keep base code change to a minimum. Let me know your thoughts or if I should try to clarify things with some code or more words.

**Comment by abellgithub** [comment]
Closing after much discussion and alternate implementation.

**Pull request closed without merging**
