### PR TITLE
Add smrmsg reader

### PR DESCRIPTION
**Pull request by gui2dev**
Applanix POSPac MMS software produces a file that describes the accuracy of the post-processed solution that contains the position, orientation and velocity RMS after smoothing.

This reader aims to allow pdal user to read that file.

### CODE REVIEW

**Comment by hobu** [comment]
Does this need to exist as its own driver, or would it be sufficient to update `readers.sbet` with these capabilities? It would be less to maintain going forward if so.

**Comment by gui2dev** [comment]
That was my first intend  but I could not find a proper way to have both files `GPSTime` to match.
It seems that there are fewer records in smrmsg than in sbet.

**Comment by hobu** [comment]
Thanks for this contribution, but we need tests before we will merge it. If you are able to add some and catch up to latest PDAL master, it can still make the 2.4 release window. Otherwise, it will be kicked ahead to 2.5.

**Comment by gui2dev** [comment]
Will do.

**Comment by gui2dev** [comment]
@hobu it's done.

**Review by hobu — APPROVED** [review]

**Pull request merged**
