### PR TITLE
TileTest.cpp: Only check read values if they are actually read

### PR DESCRIPTION
**Pull request by schwehr**

### CODE REVIEW

**Comment by abellgithub** [comment]
I don't understand this. If the file isn't good, you want to know, which is what the tests will tell you.

**Comment by aaronyonas** [comment]
The core issue here is that msan is reporting uninitialized memory reads.  That can happen, for example, if there's any trailing whitespace in the file: the loop iterates an extra time and x, y, and z are not set before they are used.

**Comment by abellgithub** [comment]
Then please remove the test on the stream that's at the end of the loop as it becomes unnecessary.

**Comment by schwehr** [comment]
Thanks!

**Pull request merged**
