### PR TITLE
Fix compilation with gcc > 7

### PR DESCRIPTION
**Pull request by pblottiere**
Hi,

I had to add some gcc flags as well as adding a header to successfully compile with gcc 7.2.0. 

BTW, the `-Werror` flag is currently duplicated so I removed the second one.

Let me know if you're interested in this PR and if I have to modify something.

And thank you for your work!

### CODE REVIEW

**Comment by abellgithub** [comment]
Will such warnings be ignored by older compilers?

**Comment by pblottiere** [comment]
> Will such warnings be ignored by older compilers?

I'm not sure... 

Otherwise, these flags may be added for gcc > 7 only. Would you prefer that?

**Comment by abellgithub** [comment]
Yes.  These warnings are unknown by earlier compilers and cause them to complain.  Thanks.

**Comment by pblottiere** [comment]
> Yes. These warnings are unknown by earlier compilers and cause them to complain.

I updated the cmake file accordingly. Let me know if it suits you.

**Pull request merged**
