### PR TITLE
GreedyProjection: Fix M_PI mingw define

### PR DESCRIPTION
**Pull request by xantares**
we must be sure to include cmath before eigen

### CODE REVIEW

**Comment by hobu** [comment]
> we must be sure to include cmath before eigen

Does eigen not work correctly or something? Does it need its own mingw patch? Remembering the magical incantation to set _USE_MATH_DEFINES and `#include <cmath>` every time we might use eigen is going to be extremely brittle. We're going to forget to do so the very next time we use eigen.

**Comment by xantares** [comment]
we can define that macro via cmake instead

**Comment by abellgithub** [comment]
What is the real problem here? That isn't described or explained.

**Comment by xantares** [comment]
@abellgithub on mingw M_PI was not defined because of some include order presumably

**Comment by abellgithub** [comment]
Fixed by similar #3523

**Pull request closed without merging**
