### PR TITLE
Add pointViewToEigen utility function

### PR DESCRIPTION
**Pull request by gadomski**
This function just converts a pointView (with x, y, z) into an x, y, z
Eigen matrix. I've written this so many times I thought I'd just put it
into PDAL.

### CODE REVIEW

**Comment by abellgithub** [comment]
Great.  But are you going to use this somewhere other than a test?

**Comment by gadomski** [comment]
Nope. I created it to be a utility function as a part of the API, for downstream users.

**Comment by abellgithub** [comment]
Could you add a comment to that effect?  I'd tend to purge code that seems dead/unused.

**Comment by gadomski** [comment]
Done.

**Comment by chambbj** [comment]
I've done something quite similar to this several other places. Definite utility! Will have to go look to see where it can be used. 👍

**Pull request merged**
